//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DTO.Catalog
{
    using System.Xml.Serialization;

    // 
    // 이 소스 코드는 xsd, 버전=4.8.3928.0에서 자동 생성되었습니다.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class OpenSCENARIO
    {

        private OpenSCENARIOFileHeader fileHeaderField;

        private OpenSCENARIOCatalog catalogField;

        /// <remarks/>
        public OpenSCENARIOFileHeader FileHeader
        {
            get
            {
                return this.fileHeaderField;
            }
            set
            {
                this.fileHeaderField = value;
            }
        }

        /// <remarks/>
        public OpenSCENARIOCatalog Catalog
        {
            get
            {
                return this.catalogField;
            }
            set
            {
                this.catalogField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOFileHeader
    {

        private byte revMajorField;

        private byte revMinorField;

        private System.DateTime dateField;

        private string descriptionField;

        private string authorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte revMajor
        {
            get
            {
                return this.revMajorField;
            }
            set
            {
                this.revMajorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte revMinor
        {
            get
            {
                return this.revMinorField;
            }
            set
            {
                this.revMinorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalog
    {

        private OpenSCENARIOCatalogVehicle[] vehicleField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Vehicle")]
        public OpenSCENARIOCatalogVehicle[] Vehicle
        {
            get
            {
                return this.vehicleField;
            }
            set
            {
                this.vehicleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalogVehicle
    {

        private OpenSCENARIOCatalogVehicleParameterDeclaration[] parameterDeclarationsField;

        private OpenSCENARIOCatalogVehiclePerformance performanceField;

        private OpenSCENARIOCatalogVehicleBoundingBox boundingBoxField;

        private OpenSCENARIOCatalogVehicleAxles axlesField;

        private OpenSCENARIOCatalogVehicleProperty[] propertiesField;

        private string nameField;

        private string vehicleCategoryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ParameterDeclaration", IsNullable = false)]
        public OpenSCENARIOCatalogVehicleParameterDeclaration[] ParameterDeclarations
        {
            get
            {
                return this.parameterDeclarationsField;
            }
            set
            {
                this.parameterDeclarationsField = value;
            }
        }

        /// <remarks/>
        public OpenSCENARIOCatalogVehiclePerformance Performance
        {
            get
            {
                return this.performanceField;
            }
            set
            {
                this.performanceField = value;
            }
        }

        /// <remarks/>
        public OpenSCENARIOCatalogVehicleBoundingBox BoundingBox
        {
            get
            {
                return this.boundingBoxField;
            }
            set
            {
                this.boundingBoxField = value;
            }
        }

        /// <remarks/>
        public OpenSCENARIOCatalogVehicleAxles Axles
        {
            get
            {
                return this.axlesField;
            }
            set
            {
                this.axlesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable = false)]
        public OpenSCENARIOCatalogVehicleProperty[] Properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vehicleCategory
        {
            get
            {
                return this.vehicleCategoryField;
            }
            set
            {
                this.vehicleCategoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalogVehicleParameterDeclaration
    {

        private string nameField;

        private string parameterTypeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parameterType
        {
            get
            {
                return this.parameterTypeField;
            }
            set
            {
                this.parameterTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalogVehiclePerformance
    {

        private decimal maxSpeedField;

        private byte maxAccelerationField;

        private decimal maxDecelerationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxSpeed
        {
            get
            {
                return this.maxSpeedField;
            }
            set
            {
                this.maxSpeedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte maxAcceleration
        {
            get
            {
                return this.maxAccelerationField;
            }
            set
            {
                this.maxAccelerationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxDeceleration
        {
            get
            {
                return this.maxDecelerationField;
            }
            set
            {
                this.maxDecelerationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalogVehicleBoundingBox
    {

        private OpenSCENARIOCatalogVehicleBoundingBoxCenter centerField;

        private OpenSCENARIOCatalogVehicleBoundingBoxDimensions dimensionsField;

        /// <remarks/>
        public OpenSCENARIOCatalogVehicleBoundingBoxCenter Center
        {
            get
            {
                return this.centerField;
            }
            set
            {
                this.centerField = value;
            }
        }

        /// <remarks/>
        public OpenSCENARIOCatalogVehicleBoundingBoxDimensions Dimensions
        {
            get
            {
                return this.dimensionsField;
            }
            set
            {
                this.dimensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalogVehicleBoundingBoxCenter
    {

        private decimal xField;

        private decimal yField;

        private decimal zField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalogVehicleBoundingBoxDimensions
    {

        private decimal widthField;

        private decimal lengthField;

        private decimal heightField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalogVehicleAxles
    {

        private OpenSCENARIOCatalogVehicleAxlesFrontAxle frontAxleField;

        private OpenSCENARIOCatalogVehicleAxlesRearAxle rearAxleField;

        /// <remarks/>
        public OpenSCENARIOCatalogVehicleAxlesFrontAxle FrontAxle
        {
            get
            {
                return this.frontAxleField;
            }
            set
            {
                this.frontAxleField = value;
            }
        }

        /// <remarks/>
        public OpenSCENARIOCatalogVehicleAxlesRearAxle RearAxle
        {
            get
            {
                return this.rearAxleField;
            }
            set
            {
                this.rearAxleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalogVehicleAxlesFrontAxle
    {

        private decimal maxSteeringField;

        private decimal wheelDiameterField;

        private decimal trackWidthField;

        private decimal positionXField;

        private decimal positionZField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxSteering
        {
            get
            {
                return this.maxSteeringField;
            }
            set
            {
                this.maxSteeringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal wheelDiameter
        {
            get
            {
                return this.wheelDiameterField;
            }
            set
            {
                this.wheelDiameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal trackWidth
        {
            get
            {
                return this.trackWidthField;
            }
            set
            {
                this.trackWidthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal positionX
        {
            get
            {
                return this.positionXField;
            }
            set
            {
                this.positionXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal positionZ
        {
            get
            {
                return this.positionZField;
            }
            set
            {
                this.positionZField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalogVehicleAxlesRearAxle
    {

        private decimal maxSteeringField;

        private decimal wheelDiameterField;

        private decimal trackWidthField;

        private decimal positionXField;

        private decimal positionZField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxSteering
        {
            get
            {
                return this.maxSteeringField;
            }
            set
            {
                this.maxSteeringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal wheelDiameter
        {
            get
            {
                return this.wheelDiameterField;
            }
            set
            {
                this.wheelDiameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal trackWidth
        {
            get
            {
                return this.trackWidthField;
            }
            set
            {
                this.trackWidthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal positionX
        {
            get
            {
                return this.positionXField;
            }
            set
            {
                this.positionXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal positionZ
        {
            get
            {
                return this.positionZField;
            }
            set
            {
                this.positionZField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OpenSCENARIOCatalogVehicleProperty
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}